#!/usr/bin/env bash

extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)  tar xjf $1      ;;
            *.tar.gz)   tar xzf $1      ;;
            *.bz2)      bunzip2 $1      ;;
            *.rar)      rar x $1        ;;
            *.gz)       gunzip $1       ;;
            *.tar)      tar xf $1       ;;
            *.tbz2)     tar xjf $1      ;;
            *.tgz)      tar xzf $1      ;;
            *.zip)      unzip $1        ;;
            *.Z)        uncompress $1   ;;
            *)          echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

_make_directory () {
        if [[ ! -d "$1" ]]; then
                mkdir -pv "$1"
        else
                echo "$1" already exists ...
        fi
}

make_and_change_directory () {
	_make_directory $1
	cd $1
}

make_and_push_directory () {
	_make_directory $1
	pushd $1
}

pophist() {
	cat $HISTFILE | awk '{print $2}' | sort -n | uniq -c | sort -n | tail
}

psg () {
        ps x | grep -v grep | grep -i ${1:-bash} --color
}

serve() {
    python -m SimpleHTTPServer ${1:-8080}
}
