#!/usr/bin/env bash

# prompt control
# info: http://www.thegeekstuff.com/2008/09/bash-shell-take-control-of-ps1-ps2-ps3-ps4-and-prompt_command/
# PS1 = the standard prompt
# PS2 = the continuation prompt
# PS3 = the select prompt (select x in set)
# PS4 = the trace prompt

case $TERM in
	xterm*|rxvt*) COLOR_PROMPT=yes;;
esac

if [[ $COLOR_PROMPT ]]; then
	source $DOTFILES/colors
	COLOR_RESET="\[${Reset}\]"
	case $OSUNAME in
		Darwin)
			USER_COLOR="\[${BWhite}\]"
			HOST_COLOR="\[${BGreen}\]"
			PWD_COLOR="\[${Yellow}\]"
			CONT_COLOR="\[${Green}\]"
			TRACE_COLOR="\[${Red}\]"
			;;
		Linux)
			USER_COLOR="\[${BCyan}\]"
			HOST_COLOR="\[${BGreen}\]"
			PWD_COLOR="\[${Yellow}\]"
			CONT_COLOR="\[${Green}\]"
			TRACE_COLOR="\[${Red}\]"
			;;
	esac
	RST="${Color_Off}"
	PS1="${USER_COLOR}\u${COLOR_RESET}@${HOST_COLOR}\h${COLOR_RESET}:${PWD_COLOR}\W${COLOR_RESET}\076 "
	PS2="${CONT_COLOR}Continue${COLOR_RESET}\302\273 "
    PS3="Choice? "
	PS4="${TRACE_COLOR}$0${RST}:${TRACE_COLOR}$LINENO${COLOR_RESET}+ "
else
	PS1='\u@\h:\w$ '
	PS2='--> '
	PS3='choice? '
	PS4='$0.$LINENO+ '
fi
