#!/usr/bin/env bash

# basic setup

# update the window size after each command
shopt -s checkwinsize

# set the os name - this gets used later
export OSUNAME=`uname`

# personalize some things for readline
export INPUTRC=$DOTFILES/readline

# set the editor
export VISUAL=vi
